### ISSUE TITLE
"message" : "Remote URL '' is not valid" when using 'artifactory_remote_repository'

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-artifactory#148]
Modifying `artifactory_remote_repository` on version 2.3.10 throws the following error

```
Error: 400 POST https://artifactory.example.com/artifactory/api/repositories/github-remote
{
  "errors" : [ {
    "status" : 400,
    "message" : "Remote URL '' is not valid"
  } ]
}
``` 

```
locals {
  allowed_github_repos = [
    "quixoten/gotee/releases/download/v*/gotee-*",
    "nats-io/gnatsd/releases/download/v*/gnatsd-*"
  ]
}
resource "artifactory_remote_repository" "github-remote" {
  key             = "github-remote"
  package_type    = "generic"
  url             = "https://github.com"
  repo_layout_ref = "simple-default"
  notes           = "managed by terraform"
  content_synchronisation {
    enabled = false
  }
  bypass_head_requests = true
  property_sets = [
    "artifactory"
  ]
  includes_pattern = join(", ", local.allowed_github_repos)
}
```

Here is the tracelog

```
artifactory_remote_repository.github-remote: Modifying... [id=github-remote]
2021/09/22 13:54:03 [DEBUG] EvalApply: ProviderMeta config value set
2021/09/22 13:54:03 [DEBUG] artifactory_remote_repository.github-remote: applying the planned Update change
2021/09/22 13:54:03 [TRACE] GRPCProvider: ApplyResourceChange
2021/09/22 13:54:03 [DEBUG] artifactory_remote_repository.github-remote: apply errored, but we're indicating that via the Error pointer rather than returning it: 400 POST https://artifactory.example.com/artifactory/api/repositories/github-remote
{
  "errors" : [ {
    "status" : 400,
    "message" : "Remote URL '' is not valid"
  } ]
}
2021-09-22T13:54:03.768-0600 [TRACE] plugin.stdio: received data: channel=STDERR len=226
2021-09-22T13:54:03.768-0600 [TRACE] plugin.stdio: waiting for stdio data
```

I'm not sure if this is a terraform or a artifactory bug. Looking at the artifactory logs it seems like terraform is passing bad data that is causing an error in artifactory
```
2021-09-22T20:01:46.333Z [jfrt ] [ERROR] [ec40edc6a5c264a6] [o.a.a.r.RestAddonImpl:1306    ] [tp-nio-8081-exec-274] - Unable to update repository: Remote URL '' is not valid
java.lang.IllegalArgumentException: Remote URL '' is not valid
	at org.artifactory.addon.repository.RemoteRepositoryCreateUpdateHelper.replaceOrUpdate(RemoteRepositoryCreateUpdateHelper.java:101)
	at org.artifactory.addon.rest.RestAddonImpl.updateRepository(RestAddonImpl.java:1257)
	at jdk.internal.reflect.GeneratedMethodAccessor2563.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy406.updateRepository(Unknown Source)
	at org.artifactory.rest.resource.repositories.RepositoriesResource.updateRepository(RepositoriesResource.java:167)
	at jdk.internal.reflect.GeneratedMethodAccessor2562.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.RepoFilter.execute(RepoFilter.java:203)
	at org.artifactory.webapp.servlet.RepoFilter.doFilter(RepoFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.AccessFilter.useAuthentication(AccessFilter.java:563)
	at org.artifactory.webapp.servlet.AccessFilter.authenticateAndExecute(AccessFilter.java:419)
	at org.artifactory.webapp.servlet.AccessFilter.doFilterInternal(AccessFilter.java:268)
	at org.artifactory.webapp.servlet.AccessFilter.doFilter(AccessFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.RequestFilter.doFilter(RequestFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.ArtifactoryCsrfFilter.doFilter(ArtifactoryCsrfFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:164)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.artifactory.webapp.servlet.SessionFilter.doFilter(SessionFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.ArtifactoryTracingFilter.doFilter(ArtifactoryTracingFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.artifactory.webapp.servlet.ArtifactoryFilter.doFilter(ArtifactoryFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:201)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:305)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at org.artifactory.addon.repository.RemoteRepositoryCreateUpdateHelper.replaceOrUpdate(RemoteRepositoryCreateUpdateHelper.java:99)
	... 79 common frames omitted

```

Looking at the artifactory API, I don't see `Remote URL` as a parameter to any api. I'm happy to get more debugging information since I can reproduce this every terraform run. I've used `TF_LOG=TRACE` but it doesn't have any relevant information. Any guidance on how to further debug this appreciated.

**Comment by chb0github** [comment]
I'll investigate. It looks like it's on the TF side and perhaps it's a case of `onemptyomit`.

**Comment by chb0github** [comment]
I just ran your code and got

```http
PUT /artifactory/api/repositories/github-remote
User-Agent: jfrog/terraform-provider-artifactory: 2.3.1
Content-Length: 455
Accept: */*
Authorization: Basic cccccc=
Content-Type: application/json
Accept-Encoding: gzip

{
  "key": "github-remote",
  "rclass": "remote",
  "packageType": "generic",
  "url": "https://github.com",
  "notes": "managed by terraform",
  "includesPattern": "quixoten/gotee/releases/download/v*/gotee-*, nats-io/gnatsd/releases/download/v*/gnatsd-*",
  "repoLayoutRef": "simple-default",
  "retrievalCachePeriodSecs": 7200,
  "propertySets": [
    "artifactory"
  ],
  "bypassHeadRequests": true,
  "contentSynchronisation": {
    "statistics": {},
    "properties": {},
    "source": {
    }
  },
  "propagateQueryParams": false
}
```

And received:
`Successfully created repository 'github-remote' `

Upon GET:

```http
GET /artifactory/api/repositories/github-remote
{
  "key" : "github-remote",
  "packageType" : "generic",
  "description" : " (local file cache)",
  "notes" : "managed by terraform",
  "includesPattern" : "quixoten/gotee/releases/download/v*/gotee-*, nats-io/gnatsd/releases/download/v*/gnatsd-*",
  "excludesPattern" : "",
  "repoLayoutRef" : "simple-default",
  "enableComposerSupport" : false,
  "enableNuGetSupport" : false,
  "enableGemsSupport" : false,
  "enableNpmSupport" : false,
  "enableBowerSupport" : false,
  "enableChefSupport" : false,
  "enableCocoaPodsSupport" : false,
  "enableConanSupport" : false,
  "enableDebianSupport" : false,
  "debianTrivialLayout" : false,
  "ddebSupported" : false,
  "enablePypiSupport" : false,
  "enablePuppetSupport" : false,
  "enableDockerSupport" : false,
  "dockerApiVersion" : "V2",
  "blockPushingSchema1" : true,
  "forceNugetAuthentication" : false,
  "enableVagrantSupport" : false,
  "enableGitLfsSupport" : false,
  "enableDistRepoSupport" : false,
  "priorityResolution" : false,
  "url" : "https://github.com",
  "username" : "",
  "password" : "",
  "handleReleases" : true,
  "handleSnapshots" : true,
  "suppressPomConsistencyChecks" : false,
  "remoteRepoChecksumPolicyType" : "generate-if-absent",
  "hardFail" : false,
  "offline" : false,
  "blackedOut" : false,
  "storeArtifactsLocally" : true,
  "socketTimeoutMillis" : 15000,
  "localAddress" : "",
  "retrievalCachePeriodSecs" : 7200,
  "assumedOfflinePeriodSecs" : 300,
  "missedRetrievalCachePeriodSecs" : 1800,
  "metadataRetrievalTimeoutSecs" : 60,
  "unusedArtifactsCleanupPeriodHours" : 0,
  "fetchJarsEagerly" : false,
  "fetchSourcesEagerly" : false,
  "shareConfiguration" : false,
  "synchronizeProperties" : false,
  "maxUniqueSnapshots" : 0,
  "maxUniqueTags" : 0,
  "propertySets" : [ "artifactory" ],
  "archiveBrowsingEnabled" : false,
  "listRemoteFolderItems" : true,
  "rejectInvalidJars" : false,
  "allowAnyHostAuth" : false,
  "enableCookieManagement" : false,
  "enableTokenAuthentication" : false,
  "propagateQueryParams" : false,
  "blockMismatchingMimeTypes" : false,
  "bypassHeadRequests" : true,
  "contentSynchronisation" : {
    "enabled" : false,
    "statistics" : {
      "enabled" : false
    },
    "properties" : {
      "enabled" : false
    },
    "source" : {
      "originAbsenceDetection" : false
    }
  },
  "externalDependenciesEnabled" : false,
  "xrayIndex" : false,
  "xrayDataTtl" : 90,
  "downloadRedirect" : false,
  "cdnRedirect" : false,
  "cargoAnonymousAccess" : false,
  "rclass" : "remote"
}
```

Things look ok here. If your RT instance is behind a load balance that is doing SSL trunking, and it's possible to connect to the host directly, then you can do as I did and get a wire sniffer out. I have been trying to somehow manage to turn on full debug out and I never get anything. I would have to turn it on with resty and direct it to TF output. The alternative is I figure out how to do a custom dump. But, that can be tricky just because I need to capture what was actually put on the wire, not what should have been. 

I am open to suggestions, but from my side, this API seems ok

**Comment by spuder** [comment]
Thank you for testing that. Our resource already exists, but we trip this error when we `update` the list. A more accurate reproduction would be to do everything you've done here, then add or remove one of these lines from `allowed_github_repos`. 

```
locals {
  allowed_github_repos = [
    "quixoten/gotee/releases/download/v*/gotee-*",
    "nats-io/gnatsd/releases/download/v*/gnatsd-*"
  ]
}
```


You've given me an idea on my side. I'll try and create a _new_ resource and verify if I can reproduce this during the `create` phase, opposed to the `update` phase. 
If you still have your test running, could you run it again so that terraform will then 'modify' the existing resource?

**Comment by chb0github** [comment]
Ok. I can try that. I have another bug I am trying to stamp out, so if you can produce some more evidence for us to work with in the meantime that'd be great

**Comment by chb0github** [comment]
I can reproduce the error and I can see that, on update, it isn't sending the URL. Digging into it

**Comment by chb0github** [comment]
Ok, I have a fix. But I must confess: I have no clue why the original code did what it did. There may be more issues lurking in this code, but for now your issue will be gone
