### ISSUE TITLE
Error: Plugin did not respond in v8.4.1

### ISSUE THREAD

**Issue by neatcoder** [jfrog/terraform-provider-artifactory#782]
**Describe the bug**
Terraform script creates a new repository with assigned permissions. Plugin is crashing on ```artifactory_permission_target``` resources. ```tf plan``` is successful and ```tf apply``` is able to create the repo but crashes when creating permission target resource. I don't see any performance issues/lags with the ```plan``` and ```apply```.

```log
Stack trace from the terraform-provider-artifactory_v8.4.1.exe plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 118 [running]:
github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security.(*PermissionTargetResourceModel).toActionsAPIModel(0x1817a00?, {0xc000d4e790?, 0x19243ff?}, {{0x0, 0x0, 0x0}, {0x1adc080, 0xc00112ebd0}, 0x0})
        github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security/resource_artifactory_permission_target.go:58 +0x47c
github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security.(*PermissionTargetResourceModel).toSectionAPIModel(0xc0006db470?, {0x1ad8aa0, 0xc000cc6540}, {{0xc0010e2220, 0x1, 0x1}, {0x1adc080, 0xc00112eae0}, 0x2})
        github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security/resource_artifactory_permission_target.go:73 +0x445
github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security.(*PermissionTargetResourceModel).toAPIModel(0xc00028cd80, {0x1ad8aa0, 0xc000cc6540})
        github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security/resource_artifactory_permission_target.go:85 +0xaf
github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security.(*PermissionTargetResource).Create(0xc000bcff08, {0x1ad8aa0, 0xc000cc6540}, {{{{0x1add840, 0xc000d51dd0}, {0x1817f40, 0xc000b25860}}, {0x1aded08, 0xc00007c4b0}}, {{{0x1add840, ...}, ...}, ...}, ...}, ...)
        github.com/jfrog/terraform-provider-artifactory/v8/pkg/artifactory/resource/security/resource_artifactory_permission_target.go:380 +0x251
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0001b8420, {0x1ad8aa0, 0xc000cc6540}, 0xc000d4f148, 0xc000d4f0e8)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/fwserver/server_createresource.go:101 +0x5b8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x1ad8aa0?, {0x1ad8aa0, 0xc000cc6540}, 0xc0003b2c80, 0xc000d4f2b8)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ApplyResourceChange(0xc0001b8420, {0x1ad8aa0?, 0xc000cc63f0?}, 0xc0003b2b90)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/proto5server/server_applyresourcechange.go:55 +0x27b
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0006db1a0, 0xc0006db200, {0xc0005a5080, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000476b40, {0x1ad8aa0?, 0xc001257ce0?}, 0xc0007f8070)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18ec640?, 0xc000476b40}, {0x1ad8aa0, 0xc001257ce0}, 0xc0007f8000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007e65a0, {0x1addb80, 0xc00017fd40}, 0xc000bc0000, 0xc000602030, 0x20b0ac0, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0007e65a0, {0x1addb80, 0xc00017fd40}, 0xc000bc0000, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
```

**Terraform code snippet**
```hcl
terraform {
  required_providers {
    artifactory = {
      source = "jfrog/artifactory"
    }
  }
}

# Configure the Artifactory provider
provider "artifactory" {
  url          = "${var.artifactory_url}/artifactory"
  access_token = var.artifactory_access_token
}

# Create a new repository
resource "artifactory_local_docker_v2_repository" "this" {
  key             = var.repository_name
  repo_layout_ref = "simple-default"
  description     = var.desc_repo
}


# Adds new repository to impacted artifactory permission targets
resource "artifactory_permission_target" "deploy_permission_upto_qa" {
  name = var.permission_target_deploy_qa
  repo {
    actions {
      groups {
        name        = var.group_developer
        permissions = var.permission_read_annotate_write
      }
      groups {
        name        = var.group_manager
        permissions = var.permission_read_annotate_write
      }
    }
    repositories     = concat([var.repository_name], var.list_repos_deploy_qa_permission)
    includes_pattern = ["**"]
  }
  depends_on = [
    artifactory_local_docker_v2_repository.this
  ]
}

resource "artifactory_permission_target" "delete_permission_upto_qa" {
  name = var.permission_target_delete_qa
  repo {
    actions {
      groups {
        name        = var.group_build_tokens
        permissions = var.permission_read_annotate_write_delete

      }
      groups {
        name        = var.group_test_build_tokens
        permissions = var.permission_read_annotate_write_delete
      }
    }
    repositories     = concat([var.repository_name], var.list_repos_delete_qa_permission)
    includes_pattern = ["**"]
  }
  depends_on = [
    artifactory_local_docker_v2_repository.this
  ]
}

# .... Few other permission targets.
```

Artifactory version: ```7.67.2```
Terraform version: ```1.5.5```
Artifactory provider version: ```8.4.1```

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform
- [X] Your version of terraform provider

**Expected behavior**
```tf apply``` should not crash after successful ```tf plan```

**Comment by danielmkn** [comment]
Hi @neatcoder, I can't reproduce the issue on my local. The configuration works with `groups`+`users` and with one of them, as well as with empty `actions` block. 
Can you try to run it with hardcoded values instead of variables?

**Comment by neatcoder** [comment]
@danielmkn Our module has evolved a bit now from the above shared snippet. However, I will give it a try.

**Comment by alexhung** [comment]
@neatcoder Any update on this issue? Is it resolved?

**Comment by alexhung** [comment]
Closing as stale issue.
